export const HTML_TERM_OF_SERVICE = `
<p><strong class="txtTermHeader" style=\"color: rgb(14, 16, 26);\">Welcome!</strong></p>
<p><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">These Terms and Conditions govern your access to and use of the Robolearn application developed by Mobisoft. By downloading, installing, or using the App, you agree to be bound by these Terms. If you do not agree to these Terms, you may not access or use the App.&nbsp;</span></p>
<p><strong class="txtTermHeader" style=\"color: rgb(14, 16, 26);\">1. Content and Ownership</strong></p>
<ul>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">The App utilizes artificial intelligence to generate stories based on your input. The content generated by the App (\"Generated Content\") is for your personal, non-commercial use only.&nbsp;</span></li>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">We claim no ownership of the ideas or concepts you provide as prompts for the App. However, you grant us a non-exclusive, royalty-free license to use the Generated Content for internal testing and improvement of the App.&nbsp;</span></li>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">You are solely responsible for ensuring you have the necessary rights (e.g., copyrights) to use the Generated Content for personal, non-commercial purposes.&nbsp;</span></li>
</ul>
<p><strong class="txtTermHeader" style=\"color: rgb(14, 16, 26);\">2. User Conduct</strong></p>
<ul>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">You agree to use the App in a lawful and ethical manner.&nbsp;</span></li>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">You will not use the App to generate content that is:&nbsp;</span>
   <ul>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">Hateful, violent, threatening, harassing, or defamatory.&nbsp;</span></li>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">Sexually explicit or obscene.&nbsp;</span></li>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">Infringes on the intellectual property rights of others.&nbsp;</span></li>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">Promotes illegal activity.&nbsp;</span></li>
   </ul>
   </li>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">We reserve the right to remove any Generated Content or terminate your access to the App if it violates these Terms.&nbsp;</span></li>
</ul>
<p><strong class="txtTermHeader" style=\"color: rgb(14, 16, 26);\">3. Disclaimer of Warranties</strong></p>
<ul>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">The App is provided \"as is\" and without warranties of any kind, express or implied. We disclaim all warranties, including merchantability, fitness for a particular purpose, and non-infringement.&nbsp;</span></li>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">We do not warrant that the App will be uninterrupted, error-free, or secure.&nbsp;</span></li>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">You acknowledge that the App utilizes artificial intelligence, and the Generated Content may not be factually accurate or complete.&nbsp;</span></li>
</ul>
<p><strong class="txtTermHeader" style=\"color: rgb(14, 16, 26);\">4. Limitation of Liability</strong></p>
<ul>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">We will not be liable for any damages arising from your use of the App, including direct, indirect, incidental, consequential, or punitive damages.&nbsp;</span></li>
</ul>
<p><strong class="txtTermHeader" style=\"color: rgb(14, 16, 26);\">5. User Data</strong></p>
<ul>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">We may collect certain information about your use of the App, such as your prompts and the Generated Content (excluding identifiable information you may have included).&nbsp;</span></li>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">We will use this information to improve the App and internal analytics.&nbsp;</span></li>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">We will not share your information with any third party without your consent except as required by law.&nbsp;</span></li>
</ul>
<p><strong class="txtTermHeader" style=\"color: rgb(14, 16, 26);\">6. Intellectual Property</strong></p>
<ul>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">The App and all intellectual property rights associated with it are owned by us or our licensors.&nbsp;</span></li>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">You are not granted any rights to our intellectual property except for the limited license to use the App as expressly permitted in these Terms.&nbsp;</span></li>
</ul>
<p><strong class="txtTermHeader" style=\"color: rgb(14, 16, 26);\">7. Termination</strong></p>
<ul>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">We may terminate your access to the App at any time and for any reason without notice.&nbsp;</span></li>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">You may terminate your access by deleting the App from your device.&nbsp;</span></li>
</ul>
<p><strong class="txtTermHeader" style=\"color: rgb(14, 16, 26);\">8. Updates and Modifications</strong></p>
<ul>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">We may update or modify the App and these Terms at any time.&nbsp;</span></li>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">Your continued use of the App following the posting of any updates or modifications constitutes your acceptance of such updates or modifications.&nbsp;</span></li>
</ul>
<p><strong class="txtTermHeader" style=\"color: rgb(14, 16, 26);\">9. Governing Law and Dispute Resolution</strong></p>
<ul>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">These Terms will be governed by and construed in accordance with the laws of the USA.&nbsp;</span></li>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">Any dispute arising out of or relating to these Terms will be subject to the exclusive jurisdiction of the courts located in the USA.&nbsp;</span></li>
</ul>
<p><strong class="txtTermHeader" style=\"color: rgb(14, 16, 26);\">10. Entire Agreement</strong></p>
<ul>
   <li><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">These Terms constitute the entire agreement between you and us regarding the use of the App.&nbsp;</span></li>
</ul>
<p><strong class="txtTermHeader" style=\"color: rgb(14, 16, 26);\">11. Contact Us</strong></p>
<p><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">If you have any questions about these Terms, please contact us at </span><a href=\"mailto:contact@mobisoft.vn\" rel=\"noopener noreferrer\" target=\"_blank\" style=\"color: rgb(70, 120, 134);\">contact@mobisoft.vn</a><span class="txtTermContent" style=\"color: rgb(14, 16, 26);\">.&nbsp;</span></p>
`;

export const HTML_PRIVACY_POLICY = `
<p><span class="txtTermContent" style="color: rgb(14, 16, 26);">This Privacy Policy describes how we collect, use, and disclose your Information in connection with your use of the Robolearn App.&nbsp;</span></p>
<p><strong class="txtTermHeader" style="color: rgb(14, 16, 26);">Information We Collect</strong></p>
<p><span class="txtTermContent" style="color: rgb(14, 16, 26);">We may collect the following Information when you use the App:&nbsp;</span></p>
<ul>
   <li><strong class="txtTermHeader" style="color: rgb(14, 16, 26);">Non-Personally Identifiable Information ("Non-PII")</strong><span class="txtTermContent" style="color: rgb(14, 16, 26);"> This may include technical Information about your device, such as device type, operating system, screen resolution, and unique device identifiers. We may also collect Information about your usage of the App, such as the features you use, the stories you generate, and the length of time you spend using the App.&nbsp;</span></li>
   <li><strong class="txtTermHeader" style="color: rgb(14, 16, 26);">Optional Information</strong><span class="txtTermContent" style="color: rgb(14, 16, 26);">: You can provide us with optional Information, such as feedback on the App or suggestions for improvement.&nbsp;</span></li>
</ul>
<p><strong class="txtTermHeader" style="color: rgb(14, 16, 26);">How We Use Your Information</strong></p>
<p><span class="txtTermContent" style="color: rgb(14, 16, 26);">We use the Information we collect for the following purposes:&nbsp;</span></p>
<ul>
   <li><span class="txtTermContent" style="color: rgb(14, 16, 26);">To operate and improve the App, we use non-PII to understand how users interact with the App and to identify and fix bugs.&nbsp;</span></li>
   <li><span class="txtTermContent" style="color: rgb(14, 16, 26);">To personalize your experience: We may use non-PII to personalize your experience with the App by suggesting story genres you might enjoy.&nbsp;</span></li>
   <li><span class="txtTermContent" style="color: rgb(14, 16, 26);">To respond to your inquiries: We may use your Information to answer your questions and requests.&nbsp;</span></li>
   <li><span class="txtTermContent" style="color: rgb(14, 16, 26);">To comply with law: We may use your Information to comply with applicable laws and regulations.&nbsp;</span></li>
</ul>
<p><strong class="txtTermHeader" style="color: rgb(14, 16, 26);">Information Sharing and Disclosure</strong></p>
<p><span class="txtTermContent" style="color: rgb(14, 16, 26);">We will not share your personal Information with any third party without your consent, except in the following cases:&nbsp;</span></p>
<ul>
   <li><strong class="txtTermHeader" style="color: rgb(14, 16, 26);">Service Providers:</strong><span class="txtTermContent" style="color: rgb(14, 16, 26);"> We may share your non-PII with service providers who help us operate the App, such as cloud storage providers or analytics providers.&nbsp;</span></li>
   <li><strong class="txtTermHeader" style="color: rgb(14, 16, 26);">Legal Requirements:</strong><span class="txtTermContent" style="color: rgb(14, 16, 26);"> We may disclose your Information if we are required to do so by law or in good faith or believe that such action is necessary to comply with legal requirements or protect our rights and safety.&nbsp;</span></li>
</ul>
<p><strong class="txtTermHeader" style="color: rgb(14, 16, 26);">Data Security</strong></p>
<p><span class="txtTermContent" style="color: rgb(14, 16, 26);">We take reasonable steps to protect the Information we collect from you from loss, misuse, unauthorized access, disclosure, alteration, and destruction. However, no internet or electronic storage system is 100% secure.&nbsp;</span></p>
<p><strong class="txtTermHeader" style="color: rgb(14, 16, 26);">Your Choices</strong></p>
<p><span class="txtTermContent" style="color: rgb(14, 16, 26);">You can choose to delete your optional Information at any time by contacting us at </span><a href="mailto:contact@mobisoft.vn" rel="noopener noreferrer" target="_blank" style="color: rgb(70, 120, 134);">contact@mobisoft.vn</a>.&nbsp;</span></p>
<p><strong class="txtTermHeader" style="color: rgb(14, 16, 26);">Children's Privacy</strong></p>
<p><span class="txtTermContent" style="color: rgb(14, 16, 26);">Our App is not directed to children under the age of 13, and we do not knowingly collect personal Information from children under 13. If you are a parent or guardian and believe your child has provided us with personal Information, please contact us. We will take steps to delete the Information from our servers.&nbsp;</span></p>
<p><strong class="txtTermHeader" style="color: rgb(14, 16, 26);">Changes to this Privacy Policy</strong></p>
<p><span class="txtTermContent" style="color: rgb(14, 16, 26);">We may update this Privacy Policy sometimes. We will notify you of any changes by posting the new Privacy Policy on the App.&nbsp;</span></p>
<p><strong class="txtTermHeader" style="color: rgb(14, 16, 26);">Contact Us</strong></p>
<p><span class="txtTermContent" style="color: rgb(14, 16, 26);">If you have any questions about this Privacy Policy, please contact us at </span><a href="mailto:contact@mobisoft.vn" rel="noopener noreferrer" target="_blank" style="color: rgb(70, 120, 134);">contact@mobisoft.vn</a>&nbsp;</p>
`;
